config {
    type: "operations",
    name: "create_view",
    dependencies: ["check_condition"]
}

DECLARE
  assertion_passed BOOL;
SET
  assertion_passed = (
  SELECT
    myresult
  FROM
    ${ref("check_condition")});
IF
  (assertion_passed IS NULL) THEN
EXECUTE IMMEDIATE
  'CREATE OR REPLACE VIEW dataform_itabak.viewbyscript AS (SELECT * from ${ref("dataform_table")} LIMIT 1)';
END IF
  ;
