config {
    type: "operations",
    name: "conditional_table_creation_o"
}

DECLARE
  my_variable STRING;
SET
  my_variable = 'O';
  -- Change this to 'K' for the other branch
  -- Branch 1: Create table if my_variable is 'O'
IF
  (my_variable = 'O') THEN
EXECUTE IMMEDIATE
  '''
  CREATE OR REPLACE TABLE dataform_itabak.table_O AS
  SELECT * from ${ref("success_table")} WHERE
  O_ORDERSTATUS = "O"
  '''
  ;
END IF
  ;
